baseurl = "/"
languageCode = "en"
title = "Codetrainee"
copyright = "© All rights reserved"
paginate = 3
publishDir= "public"

googleAnalytics = "Yout Google Analytics ID"

theme = "minimage"

[permalinks]
  post = "/:year-:month-:slug/"
  
[params]
  description = "Research blogs"
  author = "Codetrainee"
  faviconfile = "img/research.ico"               # from static/

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "Research"
    url = "/categories/Research/"

[[menu.global]]
    name = "Coding"
    url = "/categories/Coding/"

[[menu.footer]]
    name = "About"
    url = "/page/about/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
